name: Build & publish tW images
on:
  push:
    branches:
      - "master"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: amr64-2.22.1
            gs-version: 2.22.1
            label: 2.22.1
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'amd64,arm64,arm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: thinkwhere/geoserver
          tags: ${{ matrix.tag }}

      - name: Download build files
        run: |
          cd build
          chmod +x ./download.sh
          sudo ./download.sh "${{ matrix.gs-version }}"

      - name: Build and push application-base
        uses: docker/build-push-action@v4
        with:
          context: ./build
          file: ./build/Dockerfile
          build-args: |
            GS_VERSION=${{ matrix.gs-version }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
