name: Build & publish tW images
on:
  push:
    branches:
      - "docker-build"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: 2.22.2
            gs-version: 2.22.2
            label: 2.22
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download build files
        run: |
          cd build
          ./download.sh "${{ matrix.gs-version }}"`

      - name: Build and push geoserver
        uses: docker/build-push-action@v4
        with:
          context: ./build
          file: ./build/Dockerfile
          build-args: |
            GS_VERSION=${{ matrix.gs-version }}
          push: true
          tags: ${{ matrix.tag }}
          labels: ${{ matrix.label }}
